### ISSUE TITLE
[Feature Request] ISK Value Filter for Kill Feed

### ISSUE THREAD

**Issue by rinakondur** [Nathan-LS/Insight#14]
With larger groups setting up a feed can result in non stop low value kills. Would be nice to filter for any kills/losses involving 'x' over 5b ISK for example.

**Comment by Nathan-LS** [comment]
Completed in [fc5ecda](https://github.com/Nathan-LS/Insight/commit/fc5ecda9286506e081cadf2d64adcfdfe1067dd5) and now available on the public bot.
