### ISSUE TITLE
Swagger URL Change

### ISSUE THREAD

**Issue by Shadow41190** [Nathan-LS/Insight#16]
Hello, during installation, I ran into an issue where it was not pulling from the swagger URL. Come to find out it was missing a peace or had changed, by putting the new URL in fixed the issues.

docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate -i "https://esi.tech.ccp.is/_latest/swagger.json" -l python -o /local/python-client

NEW URL: https://esi.evetech.net/latest/swagger.json?datasource=tranquility

**Comment by Nathan-LS** [comment]
Updated the wiki documentation to reflect the URL change. Source installation no longer requires Docker to generate the swagger-client so that has been updated as well. Thanks!
